### ISSUE TITLE
Node.js 4 compatibility

### ISSUE THREAD

**Issue by zkochan** [xpl/stacktracey#1]
Hey! Nice package!

I'd love to use stacktracey for printing error stack for [pnpm](https://github.com/pnpm/pnpm). Actually, I already added it to the pnpm reporter: https://github.com/pnpm/pnpm-default-reporter/commit/5ecb033e17aa22f22fcb5ffda98f7412423b9907

though CI failed as stacktracey has some non-Node4-compatible syntax. As well as the `get-source` and `as-table` packages. Any objections to make these packages Node.js 4 compatible?

**Comment by xpl** [comment]
Sure, I can add a Babel transpilation step to the build pipeline of these libraries.

**Comment by xpl** [comment]
BTW, I'm now working on a Mocha integration (as a custom reporter) for a better TDD workflow: https://github.com/xpl/ololog#using-with-mocha – but this is rather experimental yet, things may not work as expected )

<img src="https://user-images.githubusercontent.com/1707/30816536-e504a9d6-a21e-11e7-976c-778a95d32219.png">

**Comment by xpl** [comment]
@zkochan Hold on, it is almost there...

**Comment by xpl** [comment]
@zkochan Hooray, now it should be compatible with Node v4!

For the `stacktracey` and `get-source` packages it required a just couple of line changes (thus not requiring Babel), and for the dependencies it turned out to be a bit more complicated. Now it seems that it works in Node 4 now, [according to Travis](https://travis-ci.org/xpl/stacktracey).

**Comment by zkochan** [comment]
Awesome! Thanks!

I'll try it tonight with pnpm. Feel free to close the issue or I'll close it once I update `pnpm-default-reporter`

**Comment by xpl** [comment]
OK, I'm closing it for now.
