### ISSUE TITLE
An option to avoid path trimming

### ISSUE THREAD

**Issue by zkochan** [xpl/stacktracey#3]
Currently, the file path is trimmed if it is longer than 40 symbols

https://github.com/xpl/stacktracey/blob/9efd80948d2988b8f4b255cc385fb36b08f85984/stacktracey.js#L228

We'd like to print the whole path when reporting errors in pnpm (https://github.com/pnpm/pnpm/issues/1317). Can an option be added to make stacktracey print the full path or to override the max length of file path

**Comment by zkochan** [comment]
fine by me

**Comment by xpl** [comment]
@zkochan Added `StackTracey.maxColumnWidths` in 09df32e18de723036ba58f7ffb709e51207e6241.

You can now override the max column widths like this:

```javascript
StackTracey.maxColumnWidths = {

    callee:     30,
    file:       40,
    sourceLine: 80
}
```

I also suggest to try making the `callee` and `sourceLine` columns smaller, so that even with a large `file` value it does not get wrapped in small displays.

**Comment by zkochan** [comment]
Thank you! I will try it
