### ISSUE TITLE
Any plans to fix Synchronous XHR?

### ISSUE THREAD

**Issue by mohammadwali** [xpl/stacktracey#5]
Right now there's a warning as Sync XHR is Deprecated. Are there any plans to fix this? I am assuming a promise wrapper can maybe a help :)

**Comment by xpl** [comment]
The synchronous loading is there by design, as I needed the source code loading working in non-async contexts (where you couldn't put an `await`). It was never intented to be used outside of the development context, so the page-blocking lag (which would've damaged the UX in an production environment) wasn't a big concern.

If Chrome really removes the API it'll have broken of course. But I don't think it happens anytime soon, as it would surely break some old codebases...

**Comment by xpl** [comment]
It would be nice to have an additional async API for fetching the sources, nevertheless.

**Comment by xpl** [comment]
@mohammadwali I have added the asynchronous methods for fetching sources and cleaning the output, see the updated README. You can now call `withSourcesAsync` and `cleanAsync` that returns awaitable Promises.

There have been some breaking changes (streamlined the overall API, removed global config variables), see the changelog for a brief description: https://github.com/xpl/stacktracey/blob/master/CHANGELOG.md#version-20-with-breaking-changes
